import Foundation
import PrayerKit

/// In-app string table. The app can run in Arabic or English regardless of the system language,
/// so strings are looked up here rather than through Bundle localizations.
struct L10n {
    let arabic: Bool

    func t(_ key: String) -> String {
        guard let pair = Self.table[key] else {
            assertionFailure("Missing localization key: \(key)")
            return key
        }
        return arabic ? pair.1 : pair.0
    }

    private static let table: [String: (String, String)] = [
        "app.name": ("Salat", "صلاة"),

        // Prayers
        "prayer.fajr": ("Fajr", "الفجر"),
        "prayer.sunrise": ("Sunrise", "الشروق"),
        "prayer.dhuhr": ("Dhuhr", "الظهر"),
        "prayer.asr": ("Asr", "العصر"),
        "prayer.maghrib": ("Maghrib", "المغرب"),
        "prayer.isha": ("Isha", "العشاء"),
        "prayer.jumuah": ("Jumuʿah", "الجمعة"),
        "extra.imsak": ("Imsak", "الإمساك"),
        "extra.midnight": ("Midnight", "منتصف الليل"),
        "extra.lastThird": ("Last third of the night", "الثلث الأخير من الليل"),

        // Popover
        "hero.next": ("Next prayer", "الصلاة القادمة"),
        "hero.at": ("at {time}", "عند {time}"),
        "day.today": ("Today", "اليوم"),
        "day.backToToday": ("Back to today", "العودة إلى اليوم"),
        "row.now": ("NOW", "الآن"),
        "row.in": ("in {d}", "بعد {d}"),
        "row.notifyOn": ("Notification on — click to turn off", "الإشعار مفعّل — انقر للإيقاف"),
        "row.notifyOff": ("Notification off — click to turn on", "الإشعار متوقف — انقر للتفعيل"),
        "row.azanOn": ("Azan on — click to turn off", "الأذان مفعّل — انقر للإيقاف"),
        "row.azanOff": ("Azan off — click to turn on", "الأذان متوقف — انقر للتفعيل"),
        "qibla": ("Qibla", "القبلة"),
        "qibla.help": ("Direction of the Kaaba, clockwise from true north", "اتجاه الكعبة بالدرجات من الشمال الجغرافي"),
        "qibla.distance": ("{km} km to Makkah", "{km} كم إلى مكة"),
        "footer.timetable": ("Monthly timetable", "الجدول الشهري"),
        "footer.widget": ("Show/hide desktop widget", "إظهار/إخفاء أداة سطح المكتب"),
        "footer.settings": ("Settings", "الإعدادات"),
        "footer.quit": ("Quit Salat", "إنهاء صلاة"),

        // Azan
        "azan.playing": ("Azan is playing", "الأذان قيد التشغيل"),
        "azan.stop": ("Stop Azan", "إيقاف الأذان"),
        "azan.sound": ("Azan sound", "صوت الأذان"),
        "azan.defaultSound": ("Azan", "الأذان"),
        "azan.fajrSound": ("Fajr azan", "أذان الفجر"),
        "azan.customFile": ("Your own audio", "ملف صوتي خاص"),
        "azan.noFile": ("None", "لا يوجد"),
        "azan.choose": ("Choose…", "اختيار…"),
        "azan.custom": ("Custom file", "ملف مخصص"),
        "azan.playback": ("Playback", "التشغيل"),
        "azan.volume": ("Volume", "مستوى الصوت"),
        "azan.fadeIn": ("Fade in gently", "رفع الصوت تدريجيًا"),
        "azan.short": ("Short azan", "أذان مختصر"),
        "azan.shortHelp": ("Plays only the opening takbir (about 30 seconds), then fades out.",
                           "يشغّل التكبير الأول فقط (نحو ٣٠ ثانية) ثم يخفت الصوت."),
        "azan.testFull": ("Play azan now", "تشغيل الأذان الآن"),
        "azan.preview": ("Preview", "معاينة"),
        "azan.note": ("Salat must be running (it lives in the menu bar) for the azan to play. Turn on “Open at login” in General.",
                      "يجب أن يكون التطبيق قيد التشغيل (في شريط القوائم) ليُرفع الأذان. فعّل «التشغيل عند تسجيل الدخول» من الإعدادات العامة."),

        // Notifications
        "notif.prayerBody": ("It's time for {prayer} prayer", "حان الآن موعد صلاة {prayer}"),
        "notif.sunriseBody": ("The sun has risen — Fajr time has ended", "أشرقت الشمس — انتهى وقت الفجر"),
        "notif.reminderTitle": ("{prayer} in {minutes} minutes", "{prayer} بعد {minutes} دقيقة"),
        "notif.reminderBody": ("Prayer time is at {time}", "موعد الصلاة {time}"),

        // Settings tabs
        "settings.title": ("Salat Settings", "إعدادات صلاة"),
        "tab.general": ("General", "عام"),
        "tab.location": ("Location", "الموقع"),
        "tab.calculation": ("Calculation", "الحساب"),
        "tab.alerts": ("Alerts", "التنبيهات"),
        "tab.azan": ("Azan", "الأذان"),
        "tab.widget": ("Widget", "الأداة"),
        "tab.about": ("About", "حول"),

        // General
        "general.language": ("Language", "اللغة"),
        "language.system": ("System", "لغة النظام"),
        "general.easternNumerals": ("Use Arabic-Indic numerals (٠١٢٣)", "استخدام الأرقام العربية المشرقية (٠١٢٣)"),
        "general.clock": ("Time format", "تنسيق الوقت"),
        "clock.system": ("System", "حسب النظام"),
        "clock.12": ("12-hour", "١٢ ساعة"),
        "clock.24": ("24-hour", "٢٤ ساعة"),
        "general.menuBar": ("Menu bar", "شريط القوائم"),
        "general.menuBarStyle": ("Show", "العرض"),
        "menubar.iconOnly": ("Icon only", "أيقونة فقط"),
        "menubar.nameAndCountdown": ("Next prayer + countdown", "الصلاة القادمة + العد التنازلي"),
        "menubar.nameAndTime": ("Next prayer + time", "الصلاة القادمة + الوقت"),
        "menubar.countdownOnly": ("Countdown only", "العد التنازلي فقط"),
        "general.menuBarSeconds": ("Show seconds in countdown", "إظهار الثواني في العد التنازلي"),
        "general.display": ("Display", "العرض"),
        "general.hijriOffset": ("Hijri date adjustment", "تعديل التاريخ الهجري"),
        "general.showImsak": ("Show Imsak", "إظهار وقت الإمساك"),
        "general.showMidnight": ("Show midnight", "إظهار منتصف الليل"),
        "general.showLastThird": ("Show last third of the night", "إظهار الثلث الأخير من الليل"),
        "general.launchAtLogin": ("Open at login", "التشغيل عند تسجيل الدخول"),

        // Location
        "location.mode": ("Location", "الموقع"),
        "location.automatic": ("Automatic", "تلقائي"),
        "location.manual": ("Manual", "يدوي"),
        "location.current": ("Current", "الحالي"),
        "location.none": ("No location set", "لم يُحدَّد موقع"),
        "location.update": ("Update now", "تحديث الآن"),
        "location.denied": ("Location access denied", "تم رفض الوصول إلى الموقع"),
        "location.failed": ("Couldn't determine location", "تعذّر تحديد الموقع"),
        "location.openPrivacy": ("Open Privacy Settings", "فتح إعدادات الخصوصية"),
        "location.search": ("Find a city", "ابحث عن مدينة"),
        "location.searchPlaceholder": ("City, address or place…", "مدينة أو عنوان أو مكان…"),
        "location.coordinates": ("Coordinates", "الإحداثيات"),
        "location.latitude": ("Latitude", "خط العرض"),
        "location.longitude": ("Longitude", "خط الطول"),
        "location.timezone": ("Time zone", "المنطقة الزمنية"),
        "location.applyCoordinates": ("Use these coordinates", "استخدام هذه الإحداثيات"),
        "compass.n": ("N", "شمال"),
        "compass.ne": ("NE", "شمال شرق"),
        "compass.e": ("E", "شرق"),
        "compass.se": ("SE", "جنوب شرق"),
        "compass.s": ("S", "جنوب"),
        "compass.sw": ("SW", "جنوب غرب"),
        "compass.w": ("W", "غرب"),
        "compass.nw": ("NW", "شمال غرب"),

        // Calculation
        "calc.method": ("Calculation method", "طريقة الحساب"),
        "calc.autoMethod": ("Choose automatically for my country", "اختيار تلقائي حسب البلد"),
        "calc.fajrAngle": ("Fajr angle", "زاوية الفجر"),
        "calc.ishaRule": ("Isha by", "العشاء حسب"),
        "calc.ishaByAngle": ("Angle", "الزاوية"),
        "calc.ishaByMinutes": ("Minutes after Maghrib", "دقائق بعد المغرب"),
        "calc.ishaAngle": ("Isha angle", "زاوية العشاء"),
        "calc.ishaMinutes": ("Minutes after Maghrib", "دقائق بعد المغرب"),
        "calc.minutesAfterMaghrib": ("{m} min after Maghrib", "{m} دقيقة بعد المغرب"),
        "calc.methodOffsets": ("official offsets (min):", "فروق رسمية (دقائق):"),
        "calc.seasonal": ("seasonal adjustment", "تعديل موسمي"),
        "calc.juristic": ("Juristic settings", "الإعدادات الفقهية"),
        "calc.asr": ("Asr", "العصر"),
        "madhab.standard": ("Standard (Shafiʿi, Maliki, Hanbali)", "الجمهور (شافعي، مالكي، حنبلي)"),
        "madhab.hanafi": ("Hanafi", "حنفي"),
        "calc.highLat": ("High latitudes", "خطوط العرض العليا"),
        "calc.highLatHelp": ("Used when the sun doesn't go deep enough below the horizon for Fajr/Isha (e.g. summer in northern Europe).",
                             "يُستخدم عندما لا تنخفض الشمس بما يكفي لتحديد الفجر أو العشاء (مثل الصيف في شمال أوروبا)."),
        "highlat.automatic": ("Automatic", "تلقائي"),
        "highlat.none": ("None", "بدون"),
        "highlat.middleOfNight": ("Middle of the night", "منتصف الليل"),
        "highlat.seventhOfNight": ("One-seventh of the night", "سُبع الليل"),
        "highlat.angleBased": ("Angle-based", "حسب الزاوية"),
        "calc.adjustments": ("Manual adjustments", "تعديلات يدوية"),
        "calc.adjustmentsHelp": ("Shift any time by a few minutes to match your local mosque.",
                                 "قدّم أو أخّر أي وقت ببضع دقائق ليتوافق مع مسجدك."),
        "calc.resetAdjustments": ("Reset adjustments", "إعادة ضبط التعديلات"),
        "unit.min": ("min", "د"),

        "method.muslimWorldLeague": ("Muslim World League", "رابطة العالم الإسلامي"),
        "method.isna": ("Islamic Society of North America (ISNA)", "الجمعية الإسلامية لأمريكا الشمالية"),
        "method.egyptian": ("Egyptian General Authority of Survey", "الهيئة المصرية العامة للمساحة"),
        "method.ummAlQura": ("Umm al-Qura, Makkah", "أم القرى، مكة المكرمة"),
        "method.karachi": ("University of Islamic Sciences, Karachi", "جامعة العلوم الإسلامية، كراتشي"),
        "method.dubai": ("Dubai (UAE)", "دبي (الإمارات)"),
        "method.gulf": ("Gulf Region", "منطقة الخليج"),
        "method.kuwait": ("Kuwait", "الكويت"),
        "method.qatar": ("Qatar", "قطر"),
        "method.moonsightingCommittee": ("Moonsighting Committee Worldwide", "لجنة رؤية الهلال العالمية"),
        "method.singapore": ("Singapore (MUIS)", "سنغافورة"),
        "method.jakim": ("Malaysia (JAKIM)", "ماليزيا"),
        "method.kemenag": ("Indonesia (Kemenag)", "إندونيسيا"),
        "method.turkey": ("Turkey (Diyanet)", "تركيا (رئاسة الشؤون الدينية)"),
        "method.tehran": ("Institute of Geophysics, Tehran", "معهد الجيوفيزياء، طهران"),
        "method.jafari": ("Shia Ithna-Ashari (Qum)", "الشيعة الإثنا عشرية (قم)"),
        "method.france": ("France (UOIF, 12°)", "فرنسا (١٢°)"),
        "method.russia": ("Russia", "روسيا"),
        "method.morocco": ("Morocco", "المغرب"),
        "method.algeria": ("Algeria", "الجزائر"),
        "method.tunisia": ("Tunisia", "تونس"),
        "method.custom": ("Custom", "مخصص"),

        // Alerts
        "alerts.perPrayer": ("Per prayer", "لكل صلاة"),
        "alerts.prayer": ("Prayer", "الصلاة"),
        "alerts.notification": ("Notification", "إشعار"),
        "alerts.azan": ("Azan", "أذان"),
        "alerts.reminder": ("Reminder", "تذكير مسبق"),
        "alerts.allOn": ("Turn all on", "تفعيل الكل"),
        "alerts.allOff": ("Turn all off", "إيقاف الكل"),
        "alerts.reminderBefore": ("Remind me before", "التذكير قبل"),
        "alerts.permission": ("Notification permission", "إذن الإشعارات"),
        "alerts.permissionGranted": ("Notifications allowed", "الإشعارات مسموحة"),
        "alerts.permissionDenied": ("Notifications are off for Salat", "الإشعارات متوقفة لتطبيق صلاة"),
        "alerts.request": ("Allow", "سماح"),
        "alerts.openSettings": ("Open System Settings", "فتح إعدادات النظام"),
        "alerts.test": ("Send test", "إرسال تجربة"),

        // Widget
        "widget.enable": ("Show widget on desktop", "إظهار الأداة على سطح المكتب"),
        "widget.size": ("Size", "الحجم"),
        "widget.size.small": ("Small", "صغير"),
        "widget.size.medium": ("Medium", "متوسط"),
        "widget.size.large": ("Large", "كبير"),
        "widget.style": ("Style", "النمط"),
        "widget.style.sky": ("Living sky", "سماء حيّة"),
        "widget.style.glass": ("Glass", "زجاجي"),
        "widget.floating": ("Keep above other windows", "إبقاؤها فوق النوافذ"),
        "widget.help": ("Drag the widget anywhere. Right-click it for options.",
                        "اسحب الأداة إلى أي مكان، وانقر بالزر الأيمن لمزيد من الخيارات."),
        "widget.preview": ("Preview", "معاينة"),
        "widget.hide": ("Hide widget", "إخفاء الأداة"),

        // Timetable
        "timetable.date": ("Date", "التاريخ"),
        "timetable.export": ("Export CSV…", "تصدير CSV…"),
        "timetable.fridayNote": ("Fridays are highlighted at Dhuhr (Jumuʿah).", "أيام الجمعة مميزة عند الظهر."),

        // About
        "about.tagline": ("Prayer times, beautifully.", "مواقيت الصلاة بأناقة."),
        "about.version": ("Version", "الإصدار"),
        "about.credits": ("Azan recordings", "تسجيلات الأذان"),
        "about.source": ("Source", "المصدر"),
        "about.calcNote": ("Times are computed on-device from solar position (no internet needed). Always defer to your local mosque.",
                           "تُحسب المواقيت على جهازك من موقع الشمس دون الحاجة للإنترنت. يُرجى الرجوع دائمًا إلى مسجدك المحلي."),

        // Welcome
        "welcome.title": ("Assalamu alaikum", "السلام عليكم"),
        "welcome.subtitle": ("Let's set up your prayer times", "لنضبط مواقيت صلاتك"),
        "welcome.detect": ("Detect", "تحديد تلقائي"),
        "welcome.searchInstead": ("Location unavailable — search for your city instead.", "الموقع غير متاح — ابحث عن مدينتك."),
        "welcome.footer": ("You can change everything later in Settings.", "يمكنك تغيير كل شيء لاحقًا من الإعدادات."),
        "welcome.loginHelp": ("Keeps Salat running so the azan plays on time.", "يُبقي التطبيق يعمل ليُرفع الأذان في وقته."),
        "welcome.start": ("Start", "ابدأ"),
    ]
}
